datasynctool: disallow options interact with DataSync
The following options - Datasync status,trigger fullsync,
enable/disable sync, list of watching paths - require live
D-Bus access for which the datasync service daemon
has to be running.

When it is not running, while trying to access the options
through the tool, then with these changes it will exit with
message indicating service is not active.

Tested:

'''
root@machine:~# datasynctool -e
Error: option is disabled — DataSync service is not active.
root@machine:~# datasynctool -f
Error: option is disabled — DataSync service is not active.
'''
Change-Id: I3e04e2f0551078fff59807d06e2f7e88db3c1fd5
Signed-off-by: Riya Sabu <riya.sabu461@gmail.com>